"""
Agent report generation and session statistics tracking.

This module handles:
- Generating handoff reports between agents
- Managing agent report memory for multi-agent workflows
- Writing session reports to disk
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from rich.console import Console

from caribou.execution.token_utils import estimate_messages_tokens, estimate_tokens


class AgentReportMemory:
    """
    Minimal memory that keeps global system prompts, the current agent prompt,
    and a collection of handoff reports generated by prior agents.
    """
    def __init__(self, global_messages: List[Dict[str, str]], agent_prompt: str) -> None:
        self._global_messages = list(global_messages)
        self._agent_prompt = agent_prompt
        self._agent_reports: List[Dict[str, str]] = []

    def update_agent_prompt(self, new_prompt: str) -> None:
        self._agent_prompt = new_prompt

    def add_report(self, agent_name: str, report: str) -> None:
        content = f"Agent report from {agent_name}:\n{report}"
        self._agent_reports.append({"role": "system", "content": content})

    def build_context(self, working_history: List[Dict[str, str]]) -> List[Dict[str, str]]:
        context: List[Dict[str, str]] = []
        context.extend(self._global_messages)
        if self._agent_prompt:
            context.append({"role": "system", "content": self._agent_prompt})
        context.extend(self._agent_reports)
        context.extend(working_history)

        # Anthropic API requires at least one non-system message
        has_non_system = any(msg.get("role") in ("user", "assistant") for msg in context)
        if not has_non_system:
            context.append({"role": "user", "content": "Continue with the next step."})

        return context

    def get_state(self) -> Dict[str, object]:
        """Read-only snapshot of report-memory state for inspection by the UI."""
        global_tokens = estimate_messages_tokens(self._global_messages)
        agent_reports_tokens = estimate_messages_tokens(self._agent_reports)
        agent_prompt_tokens = estimate_tokens(self._agent_prompt) if self._agent_prompt else 0
        total_messages = (
            len(self._global_messages) + (1 if self._agent_prompt else 0) + len(self._agent_reports)
        )
        total_tokens = global_tokens + agent_prompt_tokens + agent_reports_tokens
        return {
            "strategy": "agent_report",
            "global_message_count": len(self._global_messages),
            "report_count": len(self._agent_reports),
            "has_agent_prompt": bool(self._agent_prompt),
            "context_breakdown": {
                "pinned_system": 0,
                "pivotal_code": 0,
                "summaries": 0,
                "working_user": 0,
                "working_assistant": 0,
                "working_system": 0,
                "total": total_messages,
                "total_full_history": total_messages,
                "global_messages": len(self._global_messages),
                "agent_reports": len(self._agent_reports),
                "has_agent_prompt": bool(self._agent_prompt),
                "global_messages_tokens": global_tokens,
                "agent_reports_tokens": agent_reports_tokens,
                "agent_prompt_tokens": agent_prompt_tokens,
                "total_tokens": total_tokens,
                "total_full_history_tokens": total_tokens,
            },
        }

    def export_checkpoint(self) -> Dict[str, object]:
        return {
            "schema_version": "caribou.memory_checkpoint.agent_report.v1",
            "restorable": True,
            "global_messages": list(self._global_messages),
            "agent_prompt": self._agent_prompt,
            "agent_reports": list(self._agent_reports),
        }

    def restore_checkpoint(self, value: Dict[str, object]) -> None:
        if value.get("schema_version") != "caribou.memory_checkpoint.agent_report.v1":
            raise ValueError("unsupported agent-report memory checkpoint")
        self._global_messages = [dict(item) for item in value["global_messages"]]  # type: ignore[arg-type]
        self._agent_prompt = str(value["agent_prompt"])
        self._agent_reports = [dict(item) for item in value["agent_reports"]]  # type: ignore[arg-type]


def _write_session_report(
    console: Console,
    *,
    output_dir: Path,
    stats: Dict[str, object],
) -> Optional[Path]:
    """Persist session statistics to disk."""
    report_dir = output_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"session_report_{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.json"
    try:
        report_path.write_text(json.dumps(stats, indent=2))
        console.print(f"[bold green]✓ Session report saved to:[/bold green] {report_path}")
        return report_path
    except Exception as exc:
        console.print(f"[yellow]Warning: Failed to write session report: {exc}[/yellow]")
        return None


def _generate_agent_report(
    console: Console,
    *,
    llm_client: object,
    model_name: str,
    agent_name: str,
    history_slice: List[Dict[str, str]],
) -> str:
    """
    Ask the LLM to produce a concise handoff report for the completed agent.
    Emphasis is on data generated, file changes, and key outcomes.

    Errors from the LLM call propagate: the report is the next agent's only
    summary of this agent's work under report memory, so a session must not
    silently continue without it. An empty response is likewise an error.
    """
    if not history_slice:
        return "No history available for this agent; nothing to report."

    report_prompt = (
        "You are producing a handoff report for the previous agent in a multi-agent workflow. "
        "Summarize what the agent did, focusing on data that was generated or modified, code that was executed or changed, "
        "outputs produced (with paths if mentioned), and any warnings or blockers. "
        "Be concise but specific so the next agent can pick up where this one left off."
    )

    resp = llm_client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": report_prompt},
            {"role": "user", "content": json.dumps(history_slice)},
        ],
        temperature=0.3,
    )
    content = resp.choices[0].message.content
    if not content:
        raise RuntimeError(
            f"Handoff report LLM call for agent '{agent_name}' returned no content"
        )
    return content
